#! /usr/bin/python3
# -*- coding:utf-8 -*-

import os
import sys

if 'SCons.Script' == __name__:
    name = "db_service"

    Import(name + '_version')
    Import('env', 'install_dir', 'AddProjectSource')

    libs = ['db_core']

    src = AddProjectSource()

    env_service = env.Clone()
    env_service.AppendUnique(CPPDEFINES={'VERSION' : '\\"%s\\"' % db_service_version.VersionStr()})
    db_service = env_service.Program(name, env_service.Object(src), LIBS=libs, tools=['g++'])

    Return(name)
